services:
  postgres:
    build:
      context: api/db
      dockerfile: PostgreSQL.dockerfile
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
