### Find all devices.
GET http://localhost:3005/api/v1/devices
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}

### Create a new device.
POST http://localhost:3005/api/v1/device
Authorization: ApiKey-v1 {{$dotenv DEVICE_API_KEY}}
content-type: application/json

{
    "id": "3c2c7960-afef-4836-9a15-8312b3cfaa84",
    "name": "Demo device",
    "description": "Demo device created with REST client."
}

### Find a specific device.
GET http://localhost:3005/api/v1/device/3c2c7960-afef-4836-9a15-8312b3cfaa84
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}

### Update a device.
PUT http://localhost:3005/api/v1/device/3c2c7960-afef-4836-9a15-8312b3cfaa84
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}
content-type: application/json

{
    "name": "The new device name"
}

### Delete a device.
DELETE http://localhost:3005/api/v1/device/3c2c7960-afef-4836-9a15-8312b3cfaa84
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}