### Find all devices.
GET http://localhost:3002/api/v1/devices

### Create a new device
POST http://localhost:3002/api/v1/device
content-type: application/json

{
    "id": "3c2c7960-afef-4836-9a15-8312b3cfaa84",
    "name": "Demo device",
    "description": "Demo device created with REST client."
}

### Find a specific device.
GET http://localhost:3002/api/v1/device/3c2c7960-afef-4836-9a15-8312b3cfaa84

### Update a device.
PUT http://localhost:3002/api/v1/device/3c2c7960-afef-4836-9a15-8312b3cfaa84
content-type: application/json

{
    "name": "The new device name"
}

### Delete a device.
DELETE http://localhost:3002/api/v1/device/3c2c7960-afef-4836-9a15-8312b3cfaa84