### Find all devices.
GET http://localhost:3002/api/v1/devices

### Find a specific device.
GET http://localhost:3002/api/v1/device/205e8dce-13f7-49ef-9c61-e612b3cc80b6

### Update a device.
PUT http://localhost:3002/api/v1/device/205e8dce-13f7-49ef-9c61-e612b3cc80b6
content-type: application/json

{
    "name": "The new device name"
}

### Delete a device.
DELETE http://localhost:3002/api/v1/device/bc9b7899-05e6-44e4-8613-a9b20ad6d558