### Find all led choreos.
GET http://localhost:3002/api/v1/ledChoreos
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}

### Create a new led choreo.
POST http://localhost:3002/api/v1/ledChoreo
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}
content-type: application/json

{
    "name": "Demo LED Choreo",
    "description": "Demo LED Choreo created with REST client.",
    "type": "static",
    "data": {
        "colors": [[227, 245, 66]]
    }
}

### Find a specific led choreo.
GET http://localhost:3002/api/v1/ledChoreo/2b7ec21b-bf4f-497f-8362-c6d7ad1fb248
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}

### Update a led choreo.
PUT http://localhost:3002/api/v1/ledChoreo/2b7ec21b-bf4f-497f-8362-c6d7ad1fb248
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}
content-type: application/json

{
    "data": {
        "colors": [[227, 245, 66], [71, 245, 135]]
    }
}

### Delete a led choreo.
DELETE http://localhost:3002/api/v1/ledChoreo/2b7ec21b-bf4f-497f-8362-c6d7ad1fb248
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}