### Find all profiles.
GET http://localhost:3002/api/v1/profiles
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}

### Create a new profile.
POST http://localhost:3002/api/v1/profile
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}
content-type: application/json

{
    "name": "Demo profile",
    "description": "Demo profile created with REST client."
}

### Find a specific profile.
GET http://localhost:3002/api/v1/profile/478fc59b-06ee-4ca6-9faa-4084192abce6
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}

### Update a profile.
PUT http://localhost:3002/api/v1/profile/478fc59b-06ee-4ca6-9faa-4084192abce6
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}
content-type: application/json

{
    "name": "The new profile name"
}

### Delete a profile.
DELETE http://localhost:3002/api/v1/profile/478fc59b-06ee-4ca6-9faa-4084192abce6
Authorization: ApiKey-v1 {{$dotenv WEB_API_KEY}}